-- An toàn: chỉ ALTER nếu cột không phải NVARCHAR
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Book' AND COLUMN_NAME = 'title' AND DATA_TYPE <> 'nvarchar'
)
BEGIN
    ALTER TABLE Book ALTER COLUMN title NVARCHAR(255) NOT NULL;
END

IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Category' AND COLUMN_NAME = 'name' AND DATA_TYPE <> 'nvarchar'
)
BEGIN
    ALTER TABLE Category ALTER COLUMN name NVARCHAR(255) NOT NULL;
END
